push status

diff --git a/.github/workflows/bench.yml b/.github/workflows/bench.yml
--- a/.github/workflows/bench.yml
+++ b/.github/workflows/bench.yml
@@ -50,7 +50,7 @@ jobs:
           git config --global user.name 'GitHub Actions'
           #git config --global user.email 'build@cisco.com'
           git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
-          for attempt in $( seq 1 5 )
+          for attempt in $( seq 0 5 )
           do
             git pull --force origin
             git reset --hard
@@ -65,11 +65,12 @@ jobs:
               break
             fi
             if [ $attempt -eq 5]; then
-              false
+              echo "Git push failed after 5 attempts"
+              exit $PUSH_STATUS
+            else
+              echo "Git push failed, trying (attempt ${attempt})"
+              git reset --hard HEAD~1
+              # exponential backoff
+              sleep $(( 2 ** $attempt + $( seq 0 10 | sort -R | head -n 1 )))
             fi
-            ## TODO return failure error code if all attempts fail
-            echo "Git push failed, trying (attempt ${attempt})"
-            git reset --hard HEAD~1
-            # exponential backoff
-            sleep $(( 2 ** $attempt + $( seq 0 10 | sort -R | head -n 1 )))
           done
