push status

diff --git a/.github/workflows/bench.yml b/.github/workflows/bench.yml
--- a/.github/workflows/bench.yml
+++ b/.github/workflows/bench.yml
@@ -59,14 +59,17 @@ jobs:
             git add bench
             git status
             git commit --allow-empty -m "Upload benchmarks"
-            if git push ; then
+            ( set +e; git push )
+            PUSH_STATUS=$?
+            if [ $PUSH_STATUS -eq 0 ] ; then
               break
-            else
-              ## TODO test this branch works
-              ## TODO return failure error code if all attempts fail
-              echo "Git push failed, trying (attempt ${attempt})"
-              # exponential backoff
-              sleep $(( 2 ** $attempt + $( seq 0 10 | sort -R | head -n 1 )))
-              git reset --hard HEAD~1
             fi
+            if [ $attempt -eq 5]; then
+              false
+            fi
+            ## TODO return failure error code if all attempts fail
+            echo "Git push failed, trying (attempt ${attempt})"
+            git reset --hard HEAD~1
+            # exponential backoff
+            sleep $(( 2 ** $attempt + $( seq 0 10 | sort -R | head -n 1 )))
           done
